[package]
name = "russell_lab"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "Matrix-vector laboratory including linear algebra tools"
homepage = "https://github.com/cpmech/russell"
repository = "https://github.com/cpmech/russell"
documentation = "https://docs.rs/russell_lab"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["matrix", "vector", "linspace"]

[dependencies]
russell_chk = { path = "../russell_chk", version = "0.3" }
russell_openblas = { path = "../russell_openblas", version = "0.3" }
criterion = "0.3"
num-complex = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
serde = { version = "1.0.136", features = ["derive"] }

[dev-dependencies]
rmp-serde = "1.0.0"
serde_json = "1.0.78"

[[bench]]
name = "lab_benches"
harness = false
