[package]
name = "russell_lab"
version = "0.2.4"
edition = "2021"
license = "MIT"
description = "Matrix-vector laboratory including linear algebra tools"
homepage = "https://github.com/cpmech/russell"
repository = "https://github.com/cpmech/russell"
documentation = "https://docs.rs/russell_lab"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["matrix", "vector", "linspace"]

[dependencies]
russell_chk = { path = "../russell_chk", version = "0.2" }
russell_openblas = { path = "../russell_openblas", version = "0.2" }
criterion = "0.3"
num-traits = "0.2"
rmp-serde = "1.0.0"
serde = { version = "1.0.133", features = ["derive"] }

[[bench]]
name = "lab_benches"
harness = false
