[package]
name = "russell_stat"
version = "0.1.4"
edition = "2018"
license = "MIT"
description = "Statistics calculations, probability distributions, and pseudo random numbers"
homepage = "https://github.com/cpmech/russell"
repository = "https://github.com/cpmech/russell"
documentation = "https://docs.rs/russell_stat"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["statistics", "probability", "random", "numerical"]

[dependencies]
russell_chk = { path = "../russell_chk", version = "0.2" }
