[package]
name = "russell_sparse"
version = "0.1.0"
edition = "2018"
description = "Sparse matrix tools and solvers"
homepage = "https://github.com/cpmech/russell"
repository = "https://github.com/cpmech/russell"
documentation = "https://docs.rs/russell_sparse"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["matrix", "sparse", "solver"]

[dependencies]
russell_chk = { path = "../russell_chk", version = "0.1" }
russell_lab = { path = "../russell_lab", version = "0.1" }

[build-dependencies]
cc = "1.0"