[package]
name = "russell_sparse"
version = "0.4.1"
edition = "2021"
license = "MIT"
description = "Sparse matrix tools and solvers"
homepage = "https://github.com/cpmech/russell"
repository = "https://github.com/cpmech/russell"
documentation = "https://docs.rs/russell_sparse"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["matrix", "sparse", "solver"]

[dependencies]
russell_chk = { path = "../russell_chk", version = "0.4.1" }
russell_lab = { path = "../russell_lab", version = "0.4" }
russell_openblas = { path = "../russell_openblas", version = "0.4.1" }
structopt = "0.3"

[build-dependencies]
cc = "1.0"
