name: Compile on Windows
on: [pull_request]
jobs:
  compile_on_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            curl
            git
            python-pip
            mingw-w64-ucrt-x86_64-gcc
      - name: Install Libraries
        run: |
          bash zscripts/windows-with-intel-mkl.bash
