name: Test with Intel MKL
on: [pull_request]
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          RUSSELL_LAB_USE_INTEL_MKL: 1
          RUSSELL_SPARSE_USE_LOCAL_MUMPS: 1
          RUSSELL_SPARSE_USE_LOCAL_UMFPACK: 1
          RUSSELL_SPARSE_WITH_INTEL_DSS: 1
        run: |
          RUST_BACKTRACE=1 cargo test
