name: Test with Intel MKL
on: [pull_request]
jobs:
  test_with_intel_mkl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          bash case-b-intel-mkl-local-libs.bash
      - name: Run tests
        run: |
          source /opt/intel/oneapi/setvars.sh
          RUST_BACKTRACE=1 cargo test --features intel_mkl

