name: Test & Coverage
on: [pull_request]
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          bash case-a-openblas-debian.bash
          ls /usr/include/suitesparse