name: Test on macOS
on: [pull_request]
jobs:
  test_on_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure environment
        run: |
          echo TMPDIR=/tmp | tee -a $GITHUB_ENV
          env
      - name: Install Libraries
        run: |
          brew install lapack openblas suite-sparse
      - name: Run tests
        run: |
          sudo find /opt -iname *cblas.h*
          sudo find /opt -iname *umfpack*
          RUST_BACKTRACE=1 cargo test
