name: Test with Intel MKL
on: [pull_request]
jobs:
  test_with_intel_mkl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile MUMPS
        run: |
          bash zscripts/compile-and-install-mumps.bash mkl
      - name: Compile SuiteSparse
        run: |
          bash zscripts/compile-and-install-suitesparse.bash mkl
      - name: Run tests
        run: |
          source /opt/intel/oneapi/setvars.sh
          RUST_BACKTRACE=1 cargo test --features local_suitesparse,with_mumps,intel_mkl

