name: Test with Intel MKL
on: [pull_request]
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          bash zscripts/03-ubuntu-intel-mkl-compile.bash
      - name: Run tests
        env:
          RUSSELL_LAB_USE_INTEL_MKL: 1
          RUSSELL_SPARSE_USE_LOCAL_MUMPS: 1
          RUSSELL_SPARSE_USE_LOCAL_UMFPACK: 1
          RUSSELL_SPARSE_WITH_INTEL_DSS: 1
        run: |
          RUST_BACKTRACE=1 cargo test
