name: Test with local libs
on: [pull_request]
jobs:
  test_with_local_libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          bash case-a-openblas-local-libs.bash
      - name: Run tests
        run: |
          RUST_BACKTRACE=1 cargo test --features local_libs
