name: Test with local libs
on: [pull_request]
jobs:
  test_with_local_libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile MUMPS
        run: |
          bash zscripts/compile-and-install-mumps.bash
      - name: Compile SuiteSparse
        run: |
          bash zscripts/compile-and-install-suitesparse.bash
      - name: Run tests
        run: |
          RUST_BACKTRACE=1 cargo test --features local_suitesparse,with_mumps
